import { IntentorchAdapter } from '../ai/intentorch-adapter';
import { getAIConfig } from '../utils/config';

async function runRealTest() {
  const query = "query 2026-05-03 Guangzhou to Nanning high-speed train tickets";
  console.log(`Starting DeepSeek Full-Link Test (Round 2): "${query}"`);
  
  try {
    const aiConfig = await getAIConfig();
    console.log(`Provider: ${aiConfig.provider}, Model: ${aiConfig.model}`);

    // Create a fresh adapter instance for this test to control lifecycle
    const testAdapter = new IntentorchAdapter();
    await testAdapter.configureAI(aiConfig);
    await testAdapter.initCloudIntentEngine();

    // 1. Injected Tool Metadata
    const mockTools = [
      {
        name: "query_left_tickets",
        description: "Query 12306 ticket availability",
        serverName: "Joooook/12306-mcp",
        inputSchema: {
          type: "object",
          properties: {
            from_station: { type: "string", description: "Departure station name, e.g.: Beijing" },
            to_station: { type: "string", description: "Arrival station name, e.g.: Shanghai" },
            train_date: { type: "string", description: "Departure date, format: YYYY-MM-DD" },
            purpose_codes: { type: "string", enum: ["ADULT", "0X00"], description: "Ticket type: ADULT (adult), 0X00 (student)" }
          },
          required: ["from_station", "to_station", "train_date"]
        }
      }
    ];

    // IMPORTANT: Access engine and set tools
    const engine = (testAdapter as any).cloudIntentEngine;
    if (engine) {
        engine.setAvailableTools(mockTools);
        console.log("Tool metadata (12306-mcp) successfully bound to engine.");
    }

    // 2. Generate Plan with Real DeepSeek
    console.log("Requesting DeepSeek to analyze intent and generate plan...");
    
    // We call planQuery directly on engine to bypass getAvailableTools check in adapter
    const plan = await engine.planQuery(query);

    if (plan && plan.steps) {
      console.log("\n🎯 TEST PASSED: Plan Generated by DeepSeek!");
      console.log("--------------------------------------------------");
      const finalPlan = {
          toolSelections: plan.steps.map((step: any, idx: number) => ({
              intentId: step.id || `step-${idx}`,
              toolName: step.toolName,
              serverName: step.serverName || "Joooook/12306-mcp",
              parameters: step.arguments
          }))
      };
      console.log(JSON.stringify(finalPlan, null, 2));
      console.log("--------------------------------------------------");
      
      if (finalPlan.toolSelections.length && finalPlan.toolSelections[0].toolName === 'query_left_tickets') {
          console.log("\n✅ VERIFIED: AI correctly identified the query intent.");
          const params = finalPlan.toolSelections[0].parameters;
          console.log(`✅ VERIFIED: Routing: ${params.from_station} -> ${params.to_station}`);
          console.log(`✅ VERIFIED: Date: ${params.train_date}`);
      }
    } else {
      console.log(`\n❌ FAILED: Plan generation returned null or empty.`);
    }

  } catch (error: any) {
    console.error("\n💥 CRITICAL ERROR:", error.message);
  }
}

runRealTest();
